name: 'Publish to Hex'
description: 'Publish Elixir package to Hex.pm'
inputs:
  hex-api-key:
    description: 'Hex API key for authentication'
    required: true
  dry-run:
    description: 'Whether to perform a dry run (no actual publishing)'
    required: false
    default: 'false'
  replace:
    description: 'Whether to replace existing package version'
    required: false
    default: 'false'
  docs:
    description: 'Whether to publish documentation'
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: Compile for production
      run: MIX_ENV=prod mix compile
      shell: bash

    - name: Generate documentation
      if: inputs.docs == 'true'
      run: MIX_ENV=prod mix docs
      shell: bash

    - name: Publish to Hex (dry run)
      if: inputs.dry-run == 'true'
      env:
        HEX_API_KEY: ${{ inputs.hex-api-key }}
      run: mix hex.publish --dry-run --yes
      shell: bash

    - name: Publish to Hex
      if: inputs.dry-run == 'false'
      env:
        HEX_API_KEY: ${{ inputs.hex-api-key }}
      run: |
        if [ "${{ inputs.replace }}" = "true" ]; then
          mix hex.publish --replace --yes
        else
          mix hex.publish --yes
        fi
      shell: bash

    - name: Publish documentation
      if: inputs.docs == 'true' && inputs.dry-run == 'false'
      env:
        HEX_API_KEY: ${{ inputs.hex-api-key }}
      run: mix hex.docs
      shell: bash
